# Generated by Django 4.1 on 2022-09-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
