# Generated by Django 4.1 on 2022-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0003_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_document_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_document_verified',
            field=models.BooleanField(default=False),
        ),
    ]
