# Generated by Django 4.1 on 2022-09-01 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ref', models.CharField(default='007', max_length=200)),
                ('amount', models.CharField(max_length=30)),
                ('beneficiary_fullname', models.CharField(max_length=200)),
                ('beneficiary_address', models.CharField(max_length=200)),
                ('beneficiary_city', models.CharField(max_length=200)),
                ('beneficiary_zip', models.CharField(max_length=200)),
                ('beneficiary_country', models.CharField(max_length=200)),
                ('bank_account', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_code', models.CharField(max_length=200)),
                ('bank_address', models.CharField(max_length=200)),
                ('beneficiary_swift', models.CharField(max_length=200)),
                ('bic', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ref', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date2', models.DateTimeField(auto_now_add=True)),
                ('sent_from', models.CharField(max_length=20)),
                ('sent_to', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
