# Generated by Django 4.1 on 2022-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='acc',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
    ]
