# Generated by Django 4.1 on 2022-08-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='ref',
            field=models.CharField(default='007', max_length=200),
        ),
    ]
