# Generated by Django 4.1 on 2022-09-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_transfer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Bank_name',
            field=models.CharField(default='Absa Bank', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
