# Generated by Django 4.1 on 2022-09-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_payment_bank_name_payment_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Bank_name',
            new_name='preferred_bank',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(default='GT Bank', max_length=200),
        ),
    ]
