# Generated by Django 4.1 on 2022-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='traded_forex',
            field=models.IntegerField(),
        ),
    ]
