# Generated by Django 4.1 on 2022-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_document_traded_forex'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='employment_status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
