# Generated by Django 4.1 on 2022-08-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_document_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dob_dd',
            field=models.CharField(max_length=20),
        ),
    ]
