# Generated by Django 4.1 on 2022-08-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_document_tin_change_document_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
